# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-12 09:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('company_logo', models.ImageField(upload_to='/media//kpi_app')),
            ],
        ),
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dim_type', models.CharField(max_length=50)),
                ('level', models.IntegerField()),
                ('dim_name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kpi_app.Company')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kpi_app.Dimension')),
            ],
        ),
        migrations.CreateModel(
            name='MetricData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attr_1', models.CharField(max_length=50)),
                ('attr_2', models.CharField(max_length=50)),
                ('attr_3', models.CharField(max_length=50)),
                ('date_associated', models.DateField()),
                ('numerator', models.IntegerField()),
                ('denominator', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_status', models.IntegerField(default=True)),
                ('loaded_by', models.CharField(max_length=50)),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kpi_app.Company')),
                ('dim_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dim_1', to='kpi_app.Dimension')),
            ],
        ),
        migrations.CreateModel(
            name='Metrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(max_length=50)),
                ('metric_type', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_status', models.IntegerField()),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kpi_app.Company')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=50)),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kpi_app.Company')),
            ],
        ),
        migrations.AddField(
            model_name='metricdata',
            name='metric_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kpi_app.Metrics'),
        ),
    ]
