# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-25 14:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kpi_app', '0002_auto_20161113_0451'),
    ]

    operations = [
        migrations.CreateModel(
            name='DimensionValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('dim_name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Metrics',
            new_name='Metric',
        ),
        migrations.RemoveField(
            model_name='dimensionparent',
            name='company_name',
        ),
        migrations.RenameField(
            model_name='dimension',
            old_name='dim_name',
            new_name='dim_type',
        ),
        migrations.RemoveField(
            model_name='dimension',
            name='dim_type_id',
        ),
        migrations.RemoveField(
            model_name='dimension',
            name='level',
        ),
        migrations.RemoveField(
            model_name='dimension',
            name='parent',
        ),
        migrations.AddField(
            model_name='dimension',
            name='company_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kpi_app.Company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='metricdata',
            name='dim_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dim_1', to='kpi_app.DimensionValue'),
        ),
        migrations.DeleteModel(
            name='DimensionParent',
        ),
        migrations.AddField(
            model_name='dimensionvalue',
            name='dim_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kpi_app.Dimension'),
        ),
        migrations.AddField(
            model_name='dimensionvalue',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kpi_app.DimensionValue'),
        ),
    ]
