# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-27 03:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kpi_app', '0003_auto_20161125_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attr_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kpi_app.Company')),
            ],
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attr_name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attr_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kpi_app.Attribute')),
            ],
        ),
        migrations.AlterField(
            model_name='metricdata',
            name='attr_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attr_1', to='kpi_app.AttributeValue'),
        ),
        migrations.AlterField(
            model_name='metricdata',
            name='attr_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attr_2', to='kpi_app.AttributeValue'),
        ),
        migrations.AlterField(
            model_name='metricdata',
            name='attr_3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attr_3', to='kpi_app.AttributeValue'),
        ),
    ]
