# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-27 07:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kpi_app', '0003_auto_20161125_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attr_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attr_name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attr_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kpi_app.Attribute')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='filter1_dimValue',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='filter1', to='kpi_app.DimensionValue'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='filter2_dimValue',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='filter2', to='kpi_app.DimensionValue'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='filter3_dimValue',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='filter3', to='kpi_app.DimensionValue'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='tab3_name',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='tab4_name',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metricdata',
            name='dim_2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dim_2', to='kpi_app.DimensionValue'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metricdata',
            name='dim_3',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dim_3', to='kpi_app.DimensionValue'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='user_role',
            field=models.CharField(default='Company User', max_length=50),
        ),
        migrations.AlterField(
            model_name='metricdata',
            name='attr_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attr_1', to='kpi_app.AttributeValue'),
        ),
        migrations.AlterField(
            model_name='metricdata',
            name='attr_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attr_2', to='kpi_app.AttributeValue'),
        ),
        migrations.AlterField(
            model_name='metricdata',
            name='attr_3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attr_3', to='kpi_app.AttributeValue'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='company_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kpi_app.Company'),
        ),
    ]
