# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-27 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi_app', '0004_auto_20161127_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_logo',
            field=models.ImageField(upload_to='/media/kpi_app'),
        ),
    ]
