# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-28 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi_app', '0004_auto_20161127_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_logo',
            field=models.ImageField(default=None, upload_to='/media/kpi_app'),
        ),
        migrations.AlterField(
            model_name='company',
            name='filter1_dimValue',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='company',
            name='filter2_dimValue',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='company',
            name='filter3_dimValue',
            field=models.CharField(max_length=20),
        ),
    ]
