# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-17 13:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kpi_app', '0005_auto_20161128_0628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_logo',
            field=models.ImageField(default=None, upload_to='kpi_app'),
        ),
        migrations.AlterField(
            model_name='metricdata',
            name='attr_3',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='attr_3', to='kpi_app.AttributeValue'),
        ),
        migrations.AlterField(
            model_name='metricdata',
            name='dim_2',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='dim_2', to='kpi_app.DimensionValue'),
        ),
        migrations.AlterField(
            model_name='metricdata',
            name='dim_3',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='dim_3', to='kpi_app.DimensionValue'),
        ),
    ]
