# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-17 13:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kpi_app', '0006_auto_20161217_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metricdata',
            name='attr_3',
        ),
        migrations.RemoveField(
            model_name='metricdata',
            name='dim_2',
        ),
        migrations.RemoveField(
            model_name='metricdata',
            name='dim_3',
        ),
    ]
