# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-10 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kpi_app', '0008_privilege_role_roleprivilege_userrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='privilege',
            name='company_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kpi_app.Company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='role',
            name='company_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kpi_app.Company'),
            preserve_default=False,
        ),
    ]
