# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-12 16:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kpi_app', '0009_auto_20170110_1357'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_role',
        ),
        migrations.AddField(
            model_name='attribute',
            name='row_status',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='row_status',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='company',
            name='row_status',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='dimension',
            name='row_status',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='dimensionvalue',
            name='row_status',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='metricdata',
            name='attr_3',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='attr_3', to='kpi_app.AttributeValue'),
        ),
        migrations.AddField(
            model_name='metricdata',
            name='dim_2',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='dim_2', to='kpi_app.DimensionValue'),
        ),
        migrations.AddField(
            model_name='metricdata',
            name='dim_3',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='dim_3', to='kpi_app.DimensionValue'),
        ),
        migrations.AddField(
            model_name='privilege',
            name='row_status',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='role',
            name='row_status',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='roleprivilege',
            name='row_status',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='row_status',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='userrole',
            name='row_status',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='metric',
            name='row_status',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='roleprivilege',
            name='privilege_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='privilege_id', to='kpi_app.Privilege'),
        ),
    ]
