# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-12 17:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kpi_app', '0010_auto_20170112_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metricdata',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='metricdata',
            name='dim_1',
        ),
        migrations.RemoveField(
            model_name='metricdata',
            name='metric_id',
        ),
        migrations.DeleteModel(
            name='MetricData',
        ),
    ]
