# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-12 17:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kpi_app', '0011_auto_20170112_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_associated', models.DateField()),
                ('numerator', models.IntegerField()),
                ('denominator', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_status', models.IntegerField(default=1)),
                ('loaded_by', models.CharField(max_length=50)),
                ('attr_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attr_1', to='kpi_app.AttributeValue')),
                ('attr_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attr_2', to='kpi_app.AttributeValue')),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kpi_app.Company')),
                ('dim_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dim_1', to='kpi_app.DimensionValue')),
                ('metric_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kpi_app.Metric')),
            ],
        ),
    ]
