# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-02-01 08:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kpi_app', '0012_metricdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='metricdata',
            name='attr_3',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attr_3', to='kpi_app.AttributeValue'),
        ),
        migrations.AddField(
            model_name='metricdata',
            name='dim_2',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dim_2', to='kpi_app.DimensionValue'),
        ),
        migrations.AddField(
            model_name='metricdata',
            name='dim_3',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dim_3', to='kpi_app.DimensionValue'),
        ),
        migrations.AlterField(
            model_name='metricdata',
            name='attr_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attr_1', to='kpi_app.AttributeValue'),
        ),
        migrations.AlterField(
            model_name='metricdata',
            name='attr_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attr_2', to='kpi_app.AttributeValue'),
        ),
        migrations.AlterField(
            model_name='metricdata',
            name='dim_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dim_1', to='kpi_app.DimensionValue'),
        ),
    ]
