# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-19 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi_app', '0015_auto_20170201_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metricdata',
            name='date_associated',
            field=models.DateField(null=True),
        ),
    ]
